services:
  summarizer-backend:
    build: ./backend
    container_name: summarizer_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    environment:
      - PORT=8000

  summarizer-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: summarizer_frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - summarizer-backend